apiVersion: v1
kind: Secret
metadata: 
    name: da-core-server-certificates
type: Opaque
data: 
{{- $root := . -}}
{{- range $path, $bytes := .Files.Glob "certificates/*" }}
    {{ base $path }}: {{ $root.Files.Get $path | b64enc }}
{{- end }}
