apiVersion: v1
kind: Secret
metadata: 
    name: da-core-server-certificates
type: Opaque
data: 
{{- $cert_path := .Values.app.daCore.competentCertificateChartPath | default "certificates/competentCertificate_def.p12" -}}

{{- $root := . -}}
{{- range $path, $bytes := .Files.Glob $cert_path }}
    competentCertificate.p12: {{ $root.Files.Get $path | b64enc }}
    {{ base $path }}: {{ $root.Files.Get $path | b64enc }}
{{- end }}
